
name: DungeonGenerator


author: CAPS123987


description: Plugin that generates Dungeon


main: caps123987.DungeonGenerator.DungeonGenerator


version: ${project.version}


api-version: 1.20

permissions:
  DungeonGenerator.admin:
     description: Allows you to use DungeonGenerator admin commands
commands:
  DungeonGenerator:
     description: controls DungeonGenerator plugin
     usage: /<command>
  party:
     description: controls Dungeon party
     usage: /<command>
  boss:
    description: temp for boss room
    usage: /<command>